//
// Created by dange on 2. 1. 2024.
//

#ifndef POS_UHLAR_DVORSTIAK_SEMESTRALNA_PRACA_BOJOVNICI_OBCHOD_H
#define POS_UHLAR_DVORSTIAK_SEMESTRALNA_PRACA_BOJOVNICI_OBCHOD_H


class Obchod {
public:
    void ukazObchod();
};




#endif //POS_UHLAR_DVORSTIAK_SEMESTRALNA_PRACA_BOJOVNICI_OBCHOD_H
